<a href="https://colab.research.google.com/github/muhammed-sajid/Python/blob/main/Numpypandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Exercise 1**
Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

In [ ]:
import numpy as np

arr = np.arange(1, 11)
matrix = arr.reshape(2,5)
print("2*5 Matrix")
print(matrix)

2*5 Matrix
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


**Exercise 2**
Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.

In [ ]:
arr = np.arange(1,21)
extract = arr[5:16]
print("Extracted elements")
print(extract)


Extracted elements
[ 6  7  8  9 10 11 12 13 14 15 16]


**Exercise 3**
Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.

In [ ]:
import pandas as pd

Series = pd.Series({'apples':3, 'banana':2, 'oranges':1 })
print(Series)
Series['pears'] = 4
print("\nUpdated Series")
print(Series)

apples     3
banana     2
oranges    1
dtype: int64

Updated Series
apples     3
banana     2
oranges    1
pears      4
dtype: int64


**Exercise 4**
Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.


In [ ]:
data = {
    'name' : [f"Person {i+1}" for i in range(10)],
    'age'  : np.random.randint(18,65, size = 10),
    'gender':['Male','Female']*5
}
dataf = pd.DataFrame(data)
print(dataf)

        name  age  gender
0   Person 1   18    Male
1   Person 2   37  Female
2   Person 3   53    Male
3   Person 4   43  Female
4   Person 5   20    Male
5   Person 6   42  Female
6   Person 7   46    Male
7   Person 8   27  Female
8   Person 9   39    Male
9  Person 10   47  Female


In [ ]:
data1 = {
    'name' : ['Shyam','Ram','Alice','Shyama','Sidharth','Fathima','Zakariya','Sideek','Abhiram','Ramya'],
    'age' : [18,25,23,28,36,20,27,39,47,43],
    'genger':['Male','Male','Female','Female','Male','Female','Male','Male','Male','Female']}
df = pd.DataFrame(data1)
print(df)

       name  age  genger
0     Shyam   18    Male
1       Ram   25    Male
2     Alice   23  Female
3    Shyama   28  Female
4  Sidharth   36    Male
5   Fathima   20  Female
6  Zakariya   27    Male
7    Sideek   39    Male
8   Abhiram   47    Male
9     Ramya   43  Female


**Exercise 5**

Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.

In [ ]:


df['occupation'] = ['Programmer', 'Manager', 'Analyst'] * (len(df) // 3) + ['programmer'][:len(df) % 3]
print(df)

       name  age  genger  occupation
0     Shyam   18    Male  Programmer
1       Ram   25    Male     Manager
2     Alice   23  Female     Analyst
3    Shyama   28  Female  Programmer
4  Sidharth   36    Male     Manager
5   Fathima   20  Female     Analyst
6  Zakariya   27    Male  Programmer
7    Sideek   39    Male     Manager
8   Abhiram   47    Male     Analyst
9     Ramya   43  Female  programmer


**Exercise 6**

Select the rows of the dataframe where the age is greater than or equal to 30.

In [ ]:
filtered_df = df[df['age']>=30]
print("Filtered DataFrame")
print(filtered_df)

Filtered DataFrame
       name  age  genger  occupation
4  Sidharth   36    Male     Manager
7    Sideek   39    Male     Manager
8   Abhiram   47    Male     Analyst
9     Ramya   43  Female  programmer


**Exercise 7**

Convert this dataframe to a csv file and read that csv file, finally display the contents.

In [ ]:
csv_file ="Dataframe.csv"
df.to_csv(csv_file, index = False)
read_df = pd.read_csv(csv_file)
print("Loaded DataFrame From csv")
print(read_df)

Loaded DataFrame From csv
       name  age  genger  occupation
0     Shyam   18    Male  Programmer
1       Ram   25    Male     Manager
2     Alice   23  Female     Analyst
3    Shyama   28  Female  Programmer
4  Sidharth   36    Male     Manager
5   Fathima   20  Female     Analyst
6  Zakariya   27    Male  Programmer
7    Sideek   39    Male     Manager
8   Abhiram   47    Male     Analyst
9     Ramya   43  Female  programmer
